### PR TITLE
options object and HTML elements

### PR DESCRIPTION
**Pull request by kofifus**
This PR:

- Adds an options object with the following options:

  - startExpanded: if true starts with the json expanded
  - hideRoot: if true hides the json root 
  - hideSizeElem: if true hides sizeElem
  - useTitles: if true and object has a key '\_\_TITLE\_\_' use that instead of node.key
  - useHiddenKeys: if true hides object keys that equal '\_\_HIDDEN\_\_' (show only the value)
  - useHTML: if true assume json data is HTML

### CODE REVIEW

**Comment by cocowalla** [comment]
> useTitles: if true and object has a key '__TITLE__' use that instead of node.key
useHiddenKeys: if true hides object keys that equal '__HIDDEN__' (show only the value)

While the first 3 options are generic in nature, these last 2 are very implementation-specific; presumably they are useful for something you personally need, but IMHO I'm not sure they belong in this repo*

Also, regarding the switch from `content` to `innerHTML`, I'd personally prefer this to be _optional_ - there are times where you really don't want to display HTML, because of untrusted input, XSS etc.

* DISCLAIMER: I'm not the author/maintainer, just a happy user 😃

**Comment by kofifus** [comment]
@cocowalla 

- regarding `useTitles` and `useHiddenKeys` as they were very useful to me I assume they can be useful for others so I will leave them there unless the maintainer wishes otherwise.

- regarding making html keys/values/etc optional that is a good idea, I have now added the useHTML option for that

Thanks!

**Comment by vassudanagunta** [comment]
@kofifus 

> they were very useful to me I assume they can be useful for others so I will leave them there unless the maintainer wishes otherwise.

The concept is very useful -- in fact I was implementing my own version before I saw this. The problem with your design is requires people to change their data to fit your choices (`'__TITLE__'` and `'__HIDDEN__'`). @cocowalla is correct, this is not acceptable. **json-view** currently operates on completely generic JSON. If you are wondering why your pull request hasn't been accepted, I suspect this is the main reason.

The approach I will take, if I decide to make it generic enough to deserve a pull request, is to allow passing in a callback function that can contain custom logic for keying/naming nodes, for determining initial expand/collapse state, etc. A little like the `replacer` arg you can pass into `JSON.stringify`.

This would allow arbitrary user logic without mucking up the clean logic of **json-view**.

For example, I could pass in a `displayNamer` so that this:

``` javascript
{
    givenName: "Vas",
    surName: "Sudanagunta",
    children: [
        { givenName: "Natalia", age: 5 },
        { givenName: "Aida", age: 17 }
    ],
    address: {
        state: "NY"
        city: "Brooklyn"
        street: "718 Marcus Garvey Ave"
    }
}
```

renders as this:

```
▿ Vas Sudanagunta
  ▿ children:
    ▹ Natalia
    ▹ Aida
  ▹ address: Brooklyn, NY
```

My custom `displayNamer ` could also respond to tree state changes, so that when `address` is expanded, it renders with the normal object view with all its fields as children. When display names are used instead of the JSON keys, they would get a CSS class so they could be styled differently.  

I'm pretty sure I could do this with harming the simplicity and genericity of **json-view**.  

@pgrabovets thoughts?

**Comment by pgrabovets** [comment]
I also think it would be nice add some render options and render logic without mucking up the clean logic of json-view.

**Pull request closed without merging**
